# Generated by Django 5.2 on 2026-01-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["start"],
                "verbose_name": "予定",
                "verbose_name_plural": "予定リスト",
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="mental_load",
        ),
    ]
